# Menggunakan image base Rust resmi dari registry
FROM quay.io/fedora/fedora:latest AS builder
RUN dnf install -y rust cargo

WORKDIR /app
COPY . .
RUN cargo build --release

# Stage kedua untuk hasil yang lebih ringan
FROM quay.io/fedora/fedora-minimal:latest
WORKDIR /app
COPY --from=builder /app/target/release/my-app .
CMD ["./my-app"]